#' Generate a vector of ID codes
#'
#' `create_ind_ids` generates a new column of individual ID codes to track
#' individuals in panel survey data. The ID specification is a string in the
#' following format:
#'
#' "year entered survey" + "_" + "3 serial #" + "_" + "census ID code"
#'
#' @param data Input data with the `data.frame` type.
#' @param census_id_name The name of the column that holds grouping IDs. In the
#' CMB data, this is a census identifier, which are generated by Statistics
#' Canada.
#' @param year A string value representing the year to be included in the IDs.
#' @returns The input `data.frame` (passed to the `data` parameter) with a new
#' column holding the new individual IDs called `ind_id`.
#' @export
create_ind_ids <- function(data, census_id_name, year) {
  # Do NA conversions so something can be still be input to the ID if there is
  # `census_id` in `census_id_name` for a given row
  data[[census_id_name]] <- data[[census_id_name]] |> as.character()
  data[[census_id_name]][is.na(data[[census_id_name]])] <- "NULL"

  # Split data by census_id groups
  grouped_data <- split(data, data[[census_id_name]])
  # Apply numbering within each group
  result <- do.call(
    rbind,
    lapply(grouped_data, function(group) {
      group$ind_id <- paste(
        year,
        sprintf("%03d", seq_len(nrow(group))), # Pad with leading zeros
        group[[census_id_name]],
        sep = "_"
      )
      group
    })
  )

  # Remove temporary column and restore original row order
  result$id_within_group <- NULL
  result <- result[order(as.numeric(rownames(result))), ]
  rownames(result) <- NULL

  return(result)
}
